import examplePhoto from "../../../../public/image/listIconLightBlueNew.svg";
import { types_blocks_for_blogs } from "../../../../context/blogsContext/typesBlog";

export const data = {
  mainBlock: {
    name: "main block",
    deleting: true,
    block_name: "main block",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.MAIN_BLOCK,
    headline: "Lorem ipsum dolos",
    description:
      "Lorem ipsum dolor, sit amet consectetur adimaxime obcaecati, ipsam quasi adipisci ducimus iste praesentium deserunt a autem odio alias, eos, recusandae aliquid.",
    image: {
      name: examplePhoto,
      alt: "",
      title: "",
    },
  },
  defaultBlock: {
    name: "default block",
    deleting: true,
    block_name: "",
    block_type: types_blocks_for_blogs.DEFAULT_BLOCK,
    headline: "Lorem Ipsum",
    description:
      "Lorem ipsum io at, ut hic magnam earum tenetur praesentium distinctio placeat nihil amet id? Alias obcaecati fugit iusto atque?",
    body_text:
      "Lorem ipsum dolor sit amet cconsequatur harum quaerat repellendus tempora, odio at, ut hic magnam earum tenetur praesentium distinctio placeat nihil amet id?",
    last_text:
      "Lorem ipsumrepellendus tempora, odio at, ut hic magnam earum tenetur praesentium distinctio placeat nihil amet id?",
    list: "Lorem ipsum\n dolor sit amet\n consectetur\n adipisicing elit",
    image: {
      name: examplePhoto,
      alt: "",
      title: "",
    },
    id: `${Date.now()}`,
    styles: {
      add_top_need_more_info_button: false,
      add_bottom_need_more_info_button: false,
      main_list_number_list: false,
      last_list_number_list: false,
      body_grid_revers: false,
      background_exists: false,
      turn_padding_top: true,
      turn_padding_bottom: true,
      body_text_grid_revers: false,
      last_text_grid_revers: false,
      first_list_grid_quantity_columns: 1,
      main_list_grid_quantity_columns: 1,
      last_list_grid_quantity_columns: 1,
    },
  },

  // pricesBlock: {
  //   name: "prices block",
  //   // deleting: true,
  //   block_name: "",
  //   id: `${Date.now()}`,
  //   type_block: types_blocks_for_blogs.PRICES_BLOCK,
  //   headline: "Locksmith Costs",
  //   description:
  //     "The best and reasonable locksmith prices on the market for locksmith services are our top priority. Give us a call to get a free estimate for your locksmith's needs, whether it is an emergency or regular.\nFind out our starting prices for the most popular locksmith services, or contact us for more detailed information.",
  //   list: "Lorem ipsum##-##$47-55*\nLorem ipsum##-##$47-55*\nLorem ipsum##-##$47-55*\nLorem ipsum##-##$47-55*\nLorem ipsum##-##$47-55*",
  //   body_text:
  //     "*The final price may be different. A more accurate price will be provided depending on the specifics of the requested service, hour, service area and emergency.",
  //   last_text:
  //     "Lorem ipsumrepellendus tempora, odio at, ut hic magnam earum tenetur praesentium distinctio placeat nihil amet id?",
  //   styles: {
  //     add_top_need_more_info_button: false,
  //     add_bottom_need_more_info_button: true,
  //   },
  // },
  youMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  ayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  bayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  cayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  vayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  avayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  davayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  awdavayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  asdasavayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  awdawasdasavayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  awdasdasavayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  dawffawfasdasavayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  adwawddawffawfasdasavayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  dwadfawdawffawfasdasavayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
  awdawdawndawdawffawfasdasavayouMayAlsoLike: {
    name: "You may also like",
    deleting: true,
    block_name: "",
    id: `${Date.now()}`,
    block_type: types_blocks_for_blogs.YOU_MAY_ALSO_LIKE,
    headline: "You may also like",
    list: "cctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection\ncctv-cameras-role-privacy-and-protection",
  },
};
