import type { NextPage } from "next";
import Head from "next/head";
import BlogsComponents from "../components/blogs/blogsComponents";
import DefaultLayout from "../layout/defaultLayout";
import CreateToDoContext from "../context/blogsContext/blogsContext";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <div className={"coverIndexLogo"}>
          <img
            src="https://uadgaragedoors.com/_next/static/images/MainLogo-f6858a4d439fbe7291d4a1fc1c544f12.svg"
            width={"500px"}
          />
        </div>
      </DefaultLayout>
    </>
  );
};

export default Home;
