import Head from "next/head";
import BlogsComponents from "../../components/blogs/blogsComponents";
import DefaultLayout from "../../layout/defaultLayout";
import BlogsProvider from "../../context/blogsContext/blogsContext";

export default function BlogCreatePage() {
  return (
    <>
      <Head>
        <title>Blogs create page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <BlogsProvider>
          <BlogsComponents />
        </BlogsProvider>
      </DefaultLayout>
    </>
  );
}
