import Head from "next/head";
import DefaultLayout from "../../layout/defaultLayout";
import BlogsProvider from "../../context/blogsContext/blogsContext";
import MainPageForCreateAndPublishBlogs from "../../components/blogs/MainPageForCreateAndPublishBlogs/mainPageForCreateAndPublishBlogs";

export default function BlogsPage() {
  return (
    <>
      <Head>
        <title>Blogs main page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <BlogsProvider>
          <MainPageForCreateAndPublishBlogs />
        </BlogsProvider>
      </DefaultLayout>
    </>
  );
}
